f = open('data/data_except.txt')
ints = []
try:
    for line in f:
        # Читаем информацию из файла, преобразуем к целому числу и складываем в список
        ints.append(int(line))
except ValueError:
    # Если встречаем то, что не можем преобразовать к целому числу - выходим
    print('Это не число. Выходим.')
except:
    # Этот блок срабатывает при остальных ошибках отличных от ValueError
    print('Это что ещё такое?')
else:
    # Этот блок выполняется, если исключений во время работы не возникло
    print('Всё хорошо.')
finally:
    # Этот блок выполняется несмотря ни на что. Т.е. и при возникновении исключения и без него.
    f.close()
    print('Я закрыл файл.')

# Именно в таком порядке: try, группа except, затем else, и только потом finally.
